name: CI / CD

on:
    push:
        branches: "main"

# env:
#   IMAGE_NAME: xpto
#   AZURE_WEBAPP_NAME: xpto
 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:             
#   (clona) o reposit칩rio do GitHub para o $GITHUB_WORKSPACE, permitindo que seu fluxo de trabalho acesse e trabalhe com o c칩digo        
        -   name: Git Checkout 
            uses: actions/checkout@v4 
# Configura o Java para o GitHub Actions 
        -   name: Setup Java SDK 
            uses: actions/setup-java@v4 
            with: 
              distribution: 'temurin'  
              java-version: '21'
#   Realiza os testes unit치rios no arquivo principal do c칩digo
        -   name: Unit Tests
            run: |
                cd greenway-main
                mvn clean verify